# If the limit value is -1, there is no upper limit.
# But, "HomeListup" limit can't set value -1.
Author: "e9cef9aa627fca716f78e7d9706db4d21fddd96df7deeff9af84bf11f6c1c03a11c5025fab41b191199126329398fbdddfee58337ac65bb9c633e5bd1b2a870c"
Limit:
   InviteStack: 20
   HomeListup: 10
   HomeRegister: 30
   MuteListup: 10

Delay:
   InviteDelay: 300
   InviteRemoveDelay: 600

Mute:
   Players: []
   ShowMuters: []
   HideMuters: []
