name: SP-MServer
version: ${project.version}
main: com.github.show0611.showPlugins.mserver.Main
authors: [show0611]
description: とある鯖用に作るPlugin

commands:
   administrator:
      aliases: ["ad", "admin"]
      usage: "/<command> [args] [options]"
      permission: "sp.mserver.cmd.administrator"
      permission-message: "§cYou don't have permission execute this command."

   showplugin:
      aliases: ["sp"]
      usage: "/<command> [args] [options]"
      permission-message: "§cYou aren't this plugin developer!"

   home:
      aliases: ["h"]
      usage: "/<command> [args] [HomeName]"
      permission: "sp.mserver.cmd.home.tp"
      permission-message: "§cYou don't have permission execute this command."

   sethome:
      aliases: ["sh"]
      usage: "/<command> [HomeName]"
      permission: "sp.mserver.cmd.home.set"
      permission-message: "§cYou don't have permission execute this command."

   deletehome:
      aliases: ["dh", "dhome", "delh", "delhome"]
      usage: "/<command> [HomeName | #all]"
      permission: "sp.mserver.cmd.home.delete"
      permission-message: "§cYou don't have permission execute this command."

   listhome:
      aliases: ["lh", "lsh", "lshome", "lhome"]
      usage: "/<command>"
      permission: "sp.mserver.cmd.home.list"
      permission-message: "§cYou don't have permission execute this command."

   bedtelport:
      aliases: ["bt", "btp", "bedt", "bedtp"]
      usage: "/<command>"
      permission: "sp.mserver.cmd.home.list"
      permission-message: "§cYou don't have permission execute this command."

   showplayerdata:
      aliases: ["spd", "spdata", "splayerdata", "showpd"]
      usage: "/<command> [player]"
      permission: "sp.mserver.cmd.showplayerdata"
      permission-message: "§cYou don't have permission execute this command."

   mute:
      aliases: ["m"]
      usage: "/<command> <player>"
      permission: "sp.mserver.cmd.mute.mute"
      permission-message: "§cYou don't have permission execute this command."

   unmute:
      aliases: ["um"]
      usage: "/<command> <player>"
      permission: "sp.mserver.cmd.mute.unmute"
      permission-message: "§cYou don't have permission execute this command."

   mutedshow:
      aliases: ["ms"]
      usage: "/<command> [true, false]"
      permission: "sp.mserver.cmd.mute.show"
      permission-message: "§cYou don't have permission execute this command."

   listmute:
      aliases: ["lm", "lsm", "lsmute"]
      usage: "/<command> [page]"
      permission: "sp.mserver.cmd.mute.list"
      permission-message: "§cYou don't have permission execute this command."

   adminchat:
      aliases: ["ac", "adc"]
      usage: "/<command> <message>"
      permission: "sp.mserver.cmd.adminchat"
      permission-message: "§cYou don't have permission execute this command."

   operatorchat:
      aliases: ["oc", "opc"]
      usage: "/<command> <message>"
      permission: "sp.mserver.cmd.operatorchat"
      permission-message: "§cYou don't have permission execute this command."


permissions:
   sp.mserver.*:
      description: "If this permission is given, execution of command of this plugin is allowed."
      default: op
      children:
         sp.mserver.cmd.home.*: true
         sp.mserver.cmd.mute.*: true
         sp.mserver.cmd.showplayerdata: true
         sp.mserver.cmd.adminchat: true

   sp.mserver.cmd.home.*:
      description: "If this permission is given, execution of [home] and [sethome] command is allowed."
      default: true
      children:
         sp.mserver.cmd.home.tp: true
         sp.mserver.cmd.home.set: true
         sp.mserver.cmd.home.list: true
         sp.mserver.cmd.home.delete: true

   sp.mserver.cmd.mute.*:
      description: "If this permission is given, execution of mute command is allowed."
      default: op
      children:
         sp.mserver.cmd.mute.mute: true
         sp.mserver.cmd.mute.unmute: true
         sp.mserver.cmd.mute.show: true
         sp.mserver.cmd.mute.list: true

   sp.mserver.cmd.operatorchat:
      description: "If this permission is given, execution of oc command is allowed."
      default: op
